version: '3'
services:
  web:
    image: ket9/otus-devsecops:latest
    depends_on:
      - db
    expose:
      - "80"
    links:
      - db
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "8989:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Vdjo7#l-er"
